### ISSUE TITLE
Single Serving: Rubric Task List

### ISSUE THREAD

**Issue by jgagne** [rdoran808/gallery#1]
# Single Serving
## Rubric Task List

5 tasks (`20 points` each) with 1 extra credit task.

### Best Practices

`100 points`

- [x] Mobile-first and friendly
  - Use of a mobile-first, single-column layout for small screens, with a `max-width` and centered layout for wider screens.
- [x] Optimize all images
  - [Squoosh](https://squoosh.app): Use `MozJPEG` to optimize JPGs and use `OptiPNG` to optimize PNGs. (You may resize an image in Squoosh as well if needed.)
  - [ImageOptim](https://imageoptim.com/mac): Enable all image optimizations options (specifically `Guetzli`) via `ImageOptim` > `Preferences…` > `Enable` (left sidebar in General settings).
  - *Note:* Aim for an optimized file size around `150 KB` and below (max `200 KB`).
- [x] Validate all HTML, CSS, and color contrast
  - [Validate HTML](https://validator.w3.org/nu/) (No errors; warnings are ok, but try to resolve.)
  - [Validate CSS](http://jigsaw.w3.org/css-validator/) (No errors; warnings are ok, but try to resolve.)
  - [Color Contrast Accessibility Validator](https://color.a11y.com/) (All color combinations should pass: *Congratulations! No automated color contrast issues found on the webpage tested.*)
- [x] Audit performance, accessibility, best practices, and SEO of all pages.
  - [Measure](https://web.dev/measure/) and score 92 or above in all four categories.
- [x] Add a *description* and *URL* to the About section of your GitHub repo.
  - Share URL in `04-single-serving` channel
  - Repo should contain only essential files, and remember to use lowercase naming:
    - `index.html`
    - `css` (folder containing an external stylesheet)
      - For example: `main.css`
    - `img` (folder containing images)
      - For example: `self-portrait.jpg`
    - `README.md`
      - Update with a proper heading (title) and paragraph (description) using [Markdown](https://www.markdownguide.org/basic-syntax/).

### Extra Credit

`20 points`

- [ ] Use of single (or more) web font from Google Fonts, with a web-safe [CSS font stack](http://www.cssfontstack.com).

**Comment by jgagne** [comment]
- [x] Please re-optimize your images with [ImageOptim](https://imageoptim.com) to save 322 KB.

![imageoptim-gallery](https://user-images.githubusercontent.com/5142085/117287146-0a59f000-ae38-11eb-9b0e-2eacbb33cb5f.png)

**Comment by jgagne** [comment]
- [x] Update alt text to be more descriptive since you're not using an `h1` element as a page heading.
  -  From: `<img alt="Not Original" src="images/Not-Original-Gallery.gif" width="1622" height="450">`
  - To: `<img alt="Not Original Gallery" src="images/Not-Original-Gallery.gif" width="1622" height="450">`

**Comment by jgagne** [comment]
- [x] Update breakpoints
  - `30em` is small than the smallest resize of most browsers. Try `35em` or above. 
    - *Apply the same to your Wiki Web project.*
  - Also, consider a two-column breakpoint around `50em`.
 
**CSS Update:**

```
body {
  font-size: 100%;
}

img {
  display: block;
  max-width: 100%;
  height: auto;
  margin-left: auto;
  margin-right: auto;
  margin-top: 2em;
}

h2 {
  text-align: center;
}

.grid-image {
  display: grid;
  grid-template-columns: auto;
}

/* Breakpoint */

@media (min-width: 35em) {

  .grid-image {
    grid-template-columns: auto auto;
  }

}

/* Breakpoint */

@media (min-width: 50em) {

  body {
    font-size: 125%;
  }

  .grid-image {
    grid-template-columns: auto auto auto;
  }

  .about {
    max-width: 40em;
    margin-left: auto;
    margin-right: auto;
  }


}
```

Or simply breakpoints, and add a `max-width` breakpoint in your `body`:

```
body {
  font-size: 100%;
  max-width: 70rem;
  padding: 0 1rem;
  margin: 0 auto;
}

img {
  display: block;
  max-width: 100%;
  height: auto;
  margin-left: auto;
  margin-right: auto;
  margin-top: 2em;
}

h2 {
  text-align: center;
}

.about {
  max-width: 36rem;
  margin-left: auto;
  margin-right: auto;
}

/* Breakpoint */

@media (min-width: 30em) {

  body {
    font-size: 125%;
  }

  .grid-image {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr));
  }

}
```

**Comment by jgagne** [comment]
- [x] Update `title` to be more descriptive
 - Current: `<title>`gallery`</title>`
 - Consider: `<title>`Not Original Gallery by Ryan Doran`</title>`
